ARGS:
 tab: 'process_images'
 GPUS: 0
 cam_id: 'realsense'

 backbone: 'hrnet' #'resnet' #
 model_precision: 'fp32' # 'fp16'
 val_batch_size: 1
 nw: 4
 save_visualization_on_img: True
 mano_mesh_root_align: True
 renderer: 'pyrender'
 focal_length: 600
 FOV: 50

 mesh_cloth: 'ghostwhite' #'LightCyan'

 temporal_optimization: True
 smooth_coeff: 4.
